#!/usr/bin/env bun
/** Full isolated E2E qualification for DeepSeek/OpenRouter routes and bot fallback. */
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawn, type ChildProcessWithoutNullStreams } from "node:child_process";
import { applyRoutingPreset, logicalModelCapabilityEvidence, logicalModelCatalogRows, type RoutingPresetName } from "../src/routing/presets";
import type { OcxConfig } from "../src/types";

const root = new URL("../", import.meta.url).pathname.replace(/\/$/, "");
const port = Number(process.env.OPENCODEX_PRESET_E2E_PORT ?? "18388");
const mockPort = Number(process.env.OPENCODEX_PRESET_E2E_MOCK_PORT ?? "18389");
const temp = await mkdtemp(join(tmpdir(), "opencodex-preset-e2e-"));
const home = join(temp, "ocx"); const codex = join(temp, "codex"); await mkdir(home); await mkdir(codex);
const apiKey = `preset_e2e_${crypto.randomUUID().replaceAll("-", "")}`;
const calls: Array<{ provider: string; model: string; effort: string | null; seq: number }> = [];
let sequence = 0; let failed = new Set<string>();
function sseResponse(model: string): Response { const id = `r_${crypto.randomUUID().replaceAll("-", "")}`; const payload = { id, object: "response", created_at: 1, model, output: [{ type: "message", id: `m_${id}`, role: "assistant", content: [{ type: "output_text", text: "ROUTE_OK", annotations: [] }] }], status: "completed", usage: { input_tokens: 1, output_tokens: 1, total_tokens: 2 } }; return new Response([`event: response.created\ndata: ${JSON.stringify({ type: "response.created", response: { ...payload, output: [] } })}\n\n`, `event: response.completed\ndata: ${JSON.stringify({ type: "response.completed", response: payload })}\n\n`, "data: [DONE]\n\n"].join(""), { headers: { "content-type": "text/event-stream" } }); }
const mock = Bun.serve({ hostname: "127.0.0.1", port: mockPort, async fetch(req) { const url = new URL(req.url); if (url.pathname === "/control/fail") { const body = await req.json() as { targets?: string[] }; failed = new Set(body.targets ?? []); return Response.json({ ok: true }); } if (req.method !== "POST") return Response.json({ error: "not found" }, { status: 404 }); const body = await req.json() as Record<string, unknown>; const provider = url.pathname.split("/").filter(Boolean)[0] ?? "unknown"; const model = String(body.model ?? ""); const reasoning = body.reasoning as Record<string, unknown> | undefined; const effort = typeof reasoning?.effort === "string" ? reasoning.effort : typeof body.reasoning_effort === "string" ? body.reasoning_effort : null; calls.push({ provider, model, effort, seq: ++sequence }); if (failed.has(`${provider}/${model}`)) return Response.json({ error: { type: "server_error", message: "hard failure" } }, { status: 503 }); if (url.pathname.endsWith("/chat/completions")) return Response.json({ id: "chat", object: "chat.completion", model, choices: [{ index: 0, message: { role: "assistant", content: "ROUTE_OK" }, finish_reason: "stop" }] }); return sseResponse(model); } });
const provider = (id: string, models: string[]) => ({ adapter: "openai-responses", baseUrl: `http://127.0.0.1:${mockPort}/${id}/v1`, allowPrivateNetwork: true, apiKey: "$MOCK_UPSTREAM_API_KEY", models, liveModels: false, contextWindow: 1_000_000, maxOutputTokens: 256_000, reasoningEfforts: ["low", "medium", "high"], modelReasoningEfforts: Object.fromEntries(models.map(model => [model, ["low", "medium", "high"]])) });
const base = { port, hostname: "127.0.0.1", defaultProvider: "deepseek", providers: { openai: provider("openai", ["gpt-5.6-luna", "gpt-5.6-terra"]), openrouter: provider("openrouter", ["@preset/lstack-ling-3-0-flash"]), deepseek: provider("deepseek", ["deepseek-flash"]), "deepseek-worker": provider("deepseek-worker", ["deepseek-flash"]) }, apiKeys: [{ id: "e2e", name: "e2e", key: apiKey, createdAt: new Date().toISOString() }], clientIntegrations: { codex: false } } as unknown as OcxConfig;
let server: ChildProcessWithoutNullStreams | undefined;
async function start(preset: RoutingPresetName) { const cfg = applyRoutingPreset(base, preset); await writeFile(join(home, "config.json"), `${JSON.stringify(cfg, null, 2)}\n`, { mode: 0o600 }); server = spawn(process.execPath, ["run", "src/cli/index.ts", "start", "--port", String(port)], { cwd: root, env: { ...process.env, OPENCODEX_HOME: home, CODEX_HOME: codex, MOCK_UPSTREAM_API_KEY: "mock" }, stdio: ["ignore", "pipe", "pipe"] }); server.stderr.on("data", chunk => process.stderr.write(chunk)); for (let i = 0; i < 100; i++) { try { if ((await fetch(`http://127.0.0.1:${port}/healthz`)).ok) return; } catch {} await Bun.sleep(100); } throw new Error(`startup timeout: ${preset}`); }
async function stop() { if (!server || server.exitCode !== null) return; server.kill("SIGTERM"); await new Promise<void>(resolve => server?.once("close", () => resolve())); server = undefined; }
async function fail(targets: string[]) { await fetch(`http://127.0.0.1:${mockPort}/control/fail`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ targets }) }); }
async function ask(logical: string, effort: string) { const before = calls.length; const res = await fetch(`http://127.0.0.1:${port}/v1/responses`, { method: "POST", headers: { authorization: `Bearer ${apiKey}`, "content-type": "application/json", "x-opencodex-session-id": "e2e-session" }, body: JSON.stringify({ model: `policy/${logical}`, input: "Return exactly ROUTE_OK", reasoning: { effort }, stream: true }) }); if (!res.ok) throw new Error(`${logical}/${effort} HTTP ${res.status}: ${await res.text()}`); await res.text(); const call = calls.slice(before).at(-1); if (!call) throw new Error(`no upstream call for ${logical}/${effort}`); return call; }
function assert(ok: unknown, message: string): asserts ok { if (!ok) throw new Error(message); }
const expected: Record<string, Record<string, [string, string, string]>> = { lead: { low: ["deepseek", "deepseek-flash", "low"], medium: ["deepseek", "deepseek-flash", "high"], high: ["deepseek", "deepseek-flash", "max"] }, worker: { low: ["deepseek", "deepseek-flash", "low"], medium: ["deepseek", "deepseek-flash", "low"], high: ["deepseek", "deepseek-flash", "high"] }, expert: { low: ["deepseek", "deepseek-flash", "high"], medium: ["deepseek", "deepseek-flash", "high"], high: ["deepseek", "deepseek-flash", "high"] } };
const matrix: unknown[] = [];
try {
  await start("deepseek");
  for (const [logical, efforts] of Object.entries(expected)) for (const effort of ["low", "medium", "high"]) { const [providerName, model, wire] = efforts[effort]!; const call = await ask(logical, effort); assert(call.provider === providerName && call.model === model && call.effort === wire, `matrix mismatch ${logical}/${effort}: ${JSON.stringify({ call, expected: [providerName, model, wire] })}`); matrix.push({ preset: "deepseek", logicalModel: logical, logicalEffort: effort, routeStep: 0, provider: call.provider, model: call.model, upstreamEffort: wire, wireEffort: call.effort, evidence: "FULL_E2E", verdict: "PASS" }); }
  const deepCfg = applyRoutingPreset(base, "deepseek"); const rows = (await (await fetch(`http://127.0.0.1:${port}/v1/models`, { headers: { authorization: `Bearer ${apiKey}` } })).json() as { data: Array<Record<string, unknown>> }).data.filter(row => ["lead", "bot", "worker", "expert"].includes(String(row.id))); assert(rows.map(row => row.id).join(",") === "lead,bot,worker,expert", "deepseek logical IDs changed"); assert(rows.every(row => row.context_window === 400000 && row.max_output_tokens === 128000), `deepseek catalog policy mismatch ${JSON.stringify(rows)}`); const evidence = logicalModelCapabilityEvidence(deepCfg, { lead: 1_000_000, bot: 1_000_000, worker: 1_000_000, expert: 1_000_000 }); assert(evidence.every(item => item.catalogContextWindow === item.advertisedContextWindow && item.catalogContextWindow < item.primaryPhysicalContextWindow), "physical/advertised separation failed"); await stop();
  await start("openai"); await fail(["openrouter/@preset/lstack-ling-3-0-flash"]); for (const effort of ["low", "medium", "high"]) { const call = await ask("bot", effort); const wire = effort === "low" ? "low" : "high"; assert(call.provider === "deepseek" && call.model === "deepseek-flash" && call.effort === wire, `bot fallback mismatch ${effort}: ${JSON.stringify(call)}`); matrix.push({ preset: "openai", logicalModel: "bot", logicalEffort: effort, routeStep: 1, provider: call.provider, model: call.model, upstreamEffort: wire, wireEffort: call.effort, evidence: "FULL_E2E", verdict: "PASS" }); } await fail([]); const sticky = await ask("bot", "medium"); assert(sticky.provider === "deepseek" && sticky.effort === "high", `sticky bot fallback failed: ${JSON.stringify(sticky)}`); const low = await ask("bot", "low"); assert(low.provider === "deepseek" && low.effort === "low", `effort-scoped low binding failed: ${JSON.stringify(low)}`); await stop();
  console.log(JSON.stringify({ acceptance: "PASS", matrix, botStrictFallback: "PASS", botStickyAffinity: "PASS", catalogIds: ["lead", "bot", "worker", "expert"], physicalVsAdvertised: "PASS", note: "DeepSeek/OpenRouter isolated FULL_E2E; OpenAI-targeted cells are covered by ROUTE_PREAUTH plus separate REAL_PROVIDER_SMOKE gate" }, null, 2));
} finally { await stop().catch(() => {}); mock.stop(true); await rm(temp, { recursive: true, force: true }); const health = await fetch("http://127.0.0.1:3456/healthz").catch(() => undefined); if (!health?.ok) throw new Error("formal service health failed"); }
